### ISSUE TITLE
Agent doesn't fail on Start when there is a typo in nginx-agent.conf

### ISSUE THREAD

**Issue by inoumbaf5** [nginx/agent#171]
I'm using Agent with NGINX Management Suite. When I have a typo (syntax error) in nginx-agent.conf, restarting Agent with " systemctl restart nginx-agent" doesnt notify that there is an error.
eg:

```
nap_monitoring:
  collector_buffer_size: 50000
  processor_buffer_size: 50000
  syslog_ip: "127.0.0.1     ### Note the missing " at the end
  syslog_port: 514
```

Looking at `systemctl status nginx-agent` also doesnt show an indication that there is a syntax error 

[centos@nap-centos ~]$ sudo systemctl status nginx-agent
```
● nginx-agent.service - NGINX Agent
   Loaded: loaded (/etc/systemd/system/nginx-agent.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: exit-code) since Tue 2023-01-17 11:08:03 UTC; 4s ago
     Docs: https://github.com/nginx/agent#readme
  Process: 2441 ExecStop=/bin/sleep 3 (code=exited, status=0/SUCCESS)
  Process: 2440 ExecStop=/bin/kill -2 $MAINPID (code=exited, status=0/SUCCESS)
  Process: 2448 ExecStart=/usr/bin/nginx-agent (code=exited, status=1/FAILURE)
  Process: 2445 ExecStartPre=/bin/mkdir -p /var/log/nginx-agent (code=exited, status=0/SUCCESS)
  Process: 2444 ExecStartPre=/bin/mkdir -p /var/run/nginx-agent (code=exited, status=0/SUCCESS)
 Main PID: 2448 (code=exited, status=1/FAILURE) 
```
