### ISSUE TITLE
Prometheus metric values does not match value from NGINX Plus metrics API

### ISSUE THREAD

**Issue by leonseng** [nginx/agent#186]
I have NGINX Plus running in a Docker container, with nginx-agent installed:
```
root@0873e2df46e4:/# nginx -v
nginx version: nginx/1.23.2 (nginx-plus-r28)
root@0873e2df46e4:/# nginx-agent -v
nginx-agent version v2.22.1-a0f380fa
```

With the NGINX Plus metrics API, I can see request count of 8 for a server zone
```
root@0873e2df46e4:/# curl localhost:8080/api//6/http/server_zones/
{"status_page":{"processing":0,"requests":8,"responses":{"1xx":0,"2xx":8,"3xx":0,"4xx":0,"5xx":0,"total":8},"discarded":0,"received":4844,"sent":204308}}
```

But when accessing the nginx-agent metrics endpoint, I get a request count of 0
```
root@0873e2df46e4:/# curl -s localhost:8081/metrics/ | grep status_page | grep request_count
plus_http_request_count{display_name="0873e2df46e4",hostname="0873e2df46e4",instance_group="",nginx_id="b636d4376dea15405589692d3c5d3869ff3a9b26b0e7bb4bb1aa7e658ace1437",server_zone="status_page",system_id="ad4e5cea-3309-39d4-ad48-4688716211e6",system_tags=""} 0
```

Below are the configuration files I'm using
```
#nginx-agent.conf
log:
  level: debug
  path: /var/log/nginx-agent/
nginx:
  exclude_logs: ""
  socket: "unix:/var/run/nginx-agent/nginx.sock"
dataplane:
  status:
    poll_interval: 30s
    report_interval: 24h
metrics:
  bulk_size: 20
  report_interval: 1m
  collection_interval: 15s
  mode: aggregated
config_dirs: "/etc/nginx:/usr/local/etc/nginx:/usr/share/nginx/modules:/etc/nms"
api:
  port: 8081
```

```
# nginx.conf
user  nginx;
worker_processes  auto;
error_log  /var/log/nginx/error.log notice;
pid    /var/run/nginx.pid;
events {
  worker_connections  1024;
}
http {
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
            '$status $body_bytes_sent "$http_referer" '
            '"$http_user_agent" "$http_x_forwarded_for"';
  access_log  /var/log/nginx/access.log  main;

  upstream httpbin {
    server httpbin.org;
  }

  server {
    status_zone status_page;
    listen     80 default_server;

    location / {
      proxy_pass http://httpbin/;
    }
  }

  server {
    listen     8080;

    location /api/ {
      api write=on;
      allow all;
    }
  }
}
```
